# Generated by Django 4.2.16 on 2026-06-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='操作用户')),
                ('module', models.CharField(max_length=64, verbose_name='操作模块')),
                ('operation', models.CharField(max_length=64, verbose_name='操作类型')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('request_url', models.CharField(max_length=255, verbose_name='请求URL')),
                ('request_params', models.TextField(blank=True, default='', verbose_name='请求参数')),
                ('response_result', models.TextField(blank=True, default='', verbose_name='响应结果')),
                ('ip', models.CharField(blank=True, default='', max_length=64, verbose_name='操作IP')),
                ('status', models.SmallIntegerField(default=1, verbose_name='操作状态')),
                ('execution_time', models.IntegerField(default=0, verbose_name='执行耗时(ms)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'sys_operation_log',
                'ordering': ['-create_time'],
            },
        ),
    ]
