# Generated by Django 4.2.16 on 2026-06-10 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dict_name', models.CharField(max_length=100, verbose_name='字典名称')),
                ('dict_type', models.CharField(max_length=100, unique=True, verbose_name='字典类型编码')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('remark', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '字典类型',
                'verbose_name_plural': '字典类型',
                'db_table': 'sys_dict_type',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='DictData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dict_label', models.CharField(max_length=100, verbose_name='字典标签')),
                ('dict_value', models.CharField(max_length=100, verbose_name='字典键值')),
                ('css_class', models.CharField(blank=True, default='', max_length=100, verbose_name='样式属性')),
                ('list_class', models.CharField(blank=True, default='', max_length=100, verbose_name='表格回显样式（success/warning/danger/info）')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序号')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('remark', models.CharField(blank=True, default='', max_length=500, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('dict_type', models.ForeignKey(db_column='dict_type', on_delete=django.db.models.deletion.CASCADE, related_name='data_items', to='dict.dicttype', to_field='dict_type', verbose_name='字典类型')),
            ],
            options={
                'verbose_name': '字典数据',
                'verbose_name_plural': '字典数据',
                'db_table': 'sys_dict_data',
                'ordering': ['sort_order'],
            },
        ),
    ]
