# Generated by Django 4.2.16 on 2026-06-08 01:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_path', models.CharField(max_length=500, verbose_name='存储路径')),
                ('file_type', models.CharField(max_length=16, verbose_name='文件类型')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('chunk_count', models.IntegerField(default=0, verbose_name='分块数')),
                ('status', models.SmallIntegerField(choices=[(0, '待处理'), (1, '处理中'), (2, '已完成'), (3, '失败')], default=0, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文档',
                'db_table': 'rag_document',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('status', models.SmallIntegerField(choices=[(1, '启用'), (0, '禁用')], default=1, verbose_name='状态')),
                ('doc_count', models.IntegerField(default=0, verbose_name='文档总数')),
                ('chunk_count', models.IntegerField(default=0, verbose_name='文档块总数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '知识库',
                'db_table': 'rag_knowledge_base',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField(verbose_name='块序号')),
                ('content', models.TextField(verbose_name='内容')),
                ('vector_id', models.CharField(max_length=64, unique=True, verbose_name='向量ID')),
                ('token_count', models.IntegerField(default=0, verbose_name='Token数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='rag.document', verbose_name='所属文档')),
            ],
            options={
                'verbose_name': '文档块',
                'db_table': 'rag_document_chunk',
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='knowledge_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rag.knowledgebase', verbose_name='所属知识库'),
        ),
    ]
