# Generated by Django 4.2.16 on 2026-06-10 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='数据源名称')),
                ('db_type', models.CharField(default='mysql', max_length=20, verbose_name='数据库类型')),
                ('host', models.CharField(default='127.0.0.1', max_length=200, verbose_name='主机地址')),
                ('port', models.IntegerField(default=3306, verbose_name='端口')),
                ('db_name', models.CharField(max_length=100, verbose_name='数据库名')),
                ('username', models.CharField(default='root', max_length=100, verbose_name='用户名')),
                ('password_enc', models.CharField(blank=True, default='', max_length=500, verbose_name='密码(加密)')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('status', models.SmallIntegerField(choices=[(1, '启用'), (0, '禁用')], default=1, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '数据源',
                'verbose_name_plural': '数据源',
                'db_table': 'nl2sql_datasource',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='自然语言问题')),
                ('generated_sql', models.TextField(blank=True, default='', verbose_name='生成的 SQL')),
                ('execution_time', models.FloatField(default=0, verbose_name='执行耗时(秒)')),
                ('result_count', models.IntegerField(default=0, verbose_name='结果行数')),
                ('status', models.SmallIntegerField(choices=[(0, '失败'), (1, '成功')], default=1, verbose_name='状态')),
                ('is_favorite', models.SmallIntegerField(choices=[(0, '否'), (1, '是')], default=0, verbose_name='是否收藏')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='查询时间')),
                ('datasource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nl2sql.datasource', verbose_name='数据源')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='查询用户')),
            ],
            options={
                'verbose_name': '查询历史',
                'verbose_name_plural': '查询历史',
                'db_table': 'nl2sql_query_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
