# Generated by Django 4.2.16 on 2026-06-10 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=32, unique=True, verbose_name='学号')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('gender', models.SmallIntegerField(default=0, help_text='0=未知 1=男 2=女', verbose_name='性别')),
                ('class_name', models.CharField(blank=True, default='', max_length=64, verbose_name='班级')),
                ('major', models.CharField(blank=True, default='', max_length=128, verbose_name='专业')),
                ('college', models.CharField(blank=True, default='', max_length=128, verbose_name='学院')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, default='', max_length=128, verbose_name='邮箱')),
                ('enrollment_year', models.IntegerField(blank=True, null=True, verbose_name='入学年份')),
                ('status', models.SmallIntegerField(default=1, help_text='0=休学 1=在读 2=毕业', verbose_name='状态')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学生信息',
                'verbose_name_plural': '学生信息',
                'db_table': 'student_info',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=128, verbose_name='课程名称')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='成绩')),
                ('semester', models.CharField(help_text='如 2025-2026-1', max_length=32, verbose_name='学期')),
                ('credit', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='学分')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='student.studentinfo', verbose_name='学生')),
            ],
            options={
                'verbose_name': '学生成绩',
                'verbose_name_plural': '学生成绩',
                'db_table': 'student_score',
                'ordering': ['-create_time'],
                'unique_together': {('student', 'course_name', 'semester')},
            },
        ),
    ]
