# Generated by Django 4.2.16 on 2026-06-10 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=64, unique=True, verbose_name='角色名称')),
                ('role_key', models.CharField(max_length=64, unique=True, verbose_name='角色标识')),
                ('role_sort', models.IntegerField(default=0, verbose_name='排序号')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'sys_role',
                'ordering': ['role_sort'],
            },
        ),
        migrations.CreateModel(
            name='RoleMenuRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu', verbose_name='菜单')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.role', verbose_name='角色')),
            ],
            options={
                'db_table': 'sys_role_menu_relation',
                'unique_together': {('role', 'menu')},
            },
        ),
    ]
