# Generated by Django 6.0.5 on 2026-06-08 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolemenurelation',
            options={'verbose_name': '角色-菜单关联', 'verbose_name_plural': '角色-菜单关联'},
        ),
    ]
