# Generated by Django 4.2.16 on 2026-06-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_name', models.CharField(max_length=64, verbose_name='配置名称')),
                ('config_key', models.CharField(max_length=64, unique=True, verbose_name='配置键')),
                ('config_value', models.TextField(verbose_name='配置值')),
                ('config_type', models.SmallIntegerField(default=0, verbose_name='配置类型')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'sys_config',
                'ordering': ['sort_order'],
            },
        ),
    ]
