# Generated by Django 4.2.16 on 2026-06-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如：智谱GLM-4-Flash', max_length=100, verbose_name='配置名称')),
                ('provider', models.CharField(choices=[('zhipu', '智谱 AI'), ('dashscope', '阿里云百炼'), ('openai', 'OpenAI'), ('deepseek', 'DeepSeek'), ('other', '其他')], default='zhipu', max_length=50, verbose_name='提供商')),
                ('model_type', models.CharField(choices=[('chat', '对话模型'), ('embedding', '向量模型'), ('multimodal', '多模态模型')], max_length=20, verbose_name='模型类型')),
                ('model_name', models.CharField(help_text='如：glm-4-flash', max_length=100, verbose_name='模型名称')),
                ('api_key', models.CharField(max_length=500, verbose_name='API Key')),
                ('api_base_url', models.CharField(help_text='如：https://open.bigmodel.cn/api/paas/v4', max_length=500, verbose_name='API 地址')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('status', models.SmallIntegerField(choices=[(1, '启用'), (0, '禁用')], default=1, verbose_name='状态')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI 模型配置',
                'verbose_name_plural': 'AI 模型配置',
                'db_table': 'ai_model_config',
                'ordering': ['-is_default', '-create_time'],
            },
        ),
    ]
