# Generated by Django 6.0.5 on 2026-06-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_app', '0002_systemconfig_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='config_type',
            field=models.SmallIntegerField(choices=[(0, '文本'), (1, '数字'), (2, '布尔'), (3, 'JSON')], default=0, verbose_name='配置类型'),
        ),
    ]
