# Generated by Django 4.2.16 on 2026-06-03 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=64, verbose_name='菜单名称')),
                ('menu_type', models.SmallIntegerField(default=0, verbose_name='菜单类型')),
                ('path', models.CharField(blank=True, default='', max_length=255, verbose_name='路由路径')),
                ('component', models.CharField(blank=True, default='', max_length=255, verbose_name='组件路径')),
                ('icon', models.CharField(blank=True, default='', max_length=64, verbose_name='图标')),
                ('permission', models.CharField(blank=True, default='', max_length=64, verbose_name='权限标识')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序号')),
                ('visible', models.SmallIntegerField(default=1, verbose_name='是否可见')),
                ('is_frame', models.SmallIntegerField(default=0, verbose_name='是否外链')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menu', verbose_name='父菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'sys_menu',
                'ordering': ['sort_order'],
            },
        ),
    ]
