# Generated by Django 4.2.16 on 2026-06-10 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=64, verbose_name='部门名称')),
                ('leader', models.CharField(blank=True, default='', max_length=64, verbose_name='负责人')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, default='', max_length=128, verbose_name='邮箱')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序号')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='department.department', verbose_name='父部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
                'db_table': 'sys_department',
                'ordering': ['sort_order'],
            },
        ),
    ]
