# Generated by Django 4.2.16 on 2026-06-03 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='用户名')),
                ('nickname', models.CharField(blank=True, default='', max_length=64, verbose_name='昵称')),
                ('real_name', models.CharField(blank=True, default='', max_length=64, verbose_name='真实姓名')),
                ('email', models.EmailField(blank=True, default='', max_length=128, verbose_name='邮箱')),
                ('telephone', models.CharField(blank=True, default='', max_length=20, verbose_name='手机号')),
                ('gender', models.SmallIntegerField(default=0, verbose_name='性别')),
                ('avatar', models.CharField(blank=True, default='', max_length=255, verbose_name='头像')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='超级管理员')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'sys_user',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='UserRoleRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.role', verbose_name='角色')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'db_table': 'sys_user_role_relation',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
