# Generated by Django 6.0.5 on 2026-06-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrolerelation',
            options={'verbose_name': '用户-角色关联', 'verbose_name_plural': '用户-角色关联'},
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别'),
        ),
    ]
