# Generated by Django 4.2.16 on 2026-06-03 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(max_length=64, verbose_name='权限名称')),
                ('permission_key', models.CharField(max_length=64, unique=True, verbose_name='权限标识')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序号')),
                ('status', models.SmallIntegerField(default=1, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'sys_permission',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='MenuPermissionRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu', verbose_name='菜单')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permission.permission', verbose_name='权限')),
            ],
            options={
                'db_table': 'sys_menu_permission_relation',
                'unique_together': {('menu', 'permission')},
            },
        ),
    ]
