# Generated by Django 6.0.5 on 2026-06-08 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menupermissionrelation',
            options={'verbose_name': '菜单-权限关联', 'verbose_name_plural': '菜单-权限关联'},
        ),
    ]
